version: '3.8'

services:
  intellijob:
    build: .
    container_name: intellijob
    restart: unless-stopped
    ports:
      - '3000:3000'
    env_file:
      - .env
    volumes:
      - ./baileys_auth:/app/baileys_auth
      - ./tmp:/app/tmp
    environment:
      - NODE_ENV=production
